/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distensproject.view;

import distensproject.model.Ingredient;
import distensproject.model.InventoryTableModel;

public class Report1 extends javax.swing.JFrame {

    Ingredient[] mostUsed = new Ingredient[100];
    int[] usedMatrix = new int[1000];
    int contador;
    String most ="", minus="";
    Ingredient currentIngredient;
    
    public Report1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        lessTxtA.setEditable(false);
        moreTxtA.setEditable(false);
        generateMatrix();
        showMatrix();
    }
    
    private int usedMatrixPointer(){
        int count = 0;
        for(int i: usedMatrix){
            if(i!=0){
                count++;
            }
        }return count;
    }
        
    private void showMatrix(){
        
        int size = usedMatrixPointer();    
        for(int i = 0;i<5;i++){
            if(i<size){
                currentIngredient = getByUsed(usedMatrix[i], "most");
                if(currentIngredient!=null){
                    most += currentIngredient.getName() + ": " +currentIngredient.getUsed() + "\n";
                }            
            }    
        }
        for(int j = size-1;contador<5;j--){
            if(j<size){
                if(j>=0){
                    currentIngredient = getByUsed(usedMatrix[j], "minus");
                    if(currentIngredient!=null){
                        minus += currentIngredient.getName()+ ": " +currentIngredient.getUsed() + "\n"; 
                    }
                }
                contador++;
            }           
        }
        lessTxtA.setText(minus); 
        moreTxtA.setText(most);
    }
    
    private Ingredient getByUsed(int used, String type){
        for(Ingredient ingredient: InventoryTableModel.inventory){
            if(ingredient!=null){
                if(ingredient.getUsed()==used){
                    if(type.equals("most")){
                        if(!most.contains(ingredient.getName())){
                            return ingredient;
                        }
                    }else if(type.equals("minus")){
                        if(!minus.contains(ingredient.getName())){
                            return ingredient;
                        }
                    }
                }
            }
        }
        return null;
    }
    
    private void generateMatrix(){
        for(Ingredient ingredient: InventoryTableModel.inventory){
            if(ingredient!=null){
                usedMatrix[usedMatrixPointer()] = ingredient.getUsed();
            }
        }
        burbuja(usedMatrix);
    }
    
    private static void burbuja(int[] arreglo){
        for(int i = 0; i < arreglo.length - 1; i++){
            for(int j = 0; j < arreglo.length - 1; j++){
                if (arreglo[j] < arreglo[j + 1]){
                    int tmp = arreglo[j+1];
                    arreglo[j+1] = arreglo[j];
                    arreglo[j] = tmp;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        moreTxtA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lessTxtA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moreTxtA.setColumns(20);
        moreTxtA.setRows(5);
        jScrollPane1.setViewportView(moreTxtA);

        lessTxtA.setColumns(20);
        lessTxtA.setRows(5);
        jScrollPane2.setViewportView(lessTxtA);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("5 ingredientes mas usados");

        acceptBtn.setText("Aceptar");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("5 ingredientes menos usados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(acceptBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        this.dispose();
        Reports reports = new Reports();
        reports.setVisible(true);
    }//GEN-LAST:event_acceptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lessTxtA;
    private javax.swing.JTextArea moreTxtA;
    // End of variables declaration//GEN-END:variables
}
